server {
    listen 443 ssl;
    server_name 192.168.1.144 100.97.175.6;

    ssl_certificate /certs/grocy.crt;
    ssl_certificate_key /certs/grocy.key;

    location / {
        proxy_pass http://grocy:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
